name: Bug Report
description: Report a bug with the PM Skills MCP server
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve pm-skills-mcp!

        **Note:** For issues with skill content (templates, examples), please report to [pm-skills](https://github.com/product-on-purpose/pm-skills/issues).

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the MCP server has the issue?
      options:
        - MCP Server / Connection
        - Tool execution
        - Resource access
        - Prompt generation
        - Build / Installation
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What went wrong?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Configure MCP server in Claude Desktop...
        2. Call tool with parameters...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide:
        - OS: [e.g., macOS 14.0, Windows 11, Ubuntu 22.04]
        - Node.js version: [e.g., 20.x]
        - MCP Client: [e.g., Claude Desktop, custom client]
        - pm-skills-mcp version: [e.g., 0.1.2]
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Include any relevant error messages or logs
      render: shell
    validations:
      required: false
